
package sample.helper.webService.wsGeneratedFiles;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotificationsWebInterface", targetNamespace = "http://webService.helper.sample/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NotificationsWebInterface {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "notifyChatManager", targetNamespace = "http://webService.helper.sample/", className = "sample.helper.webService.wsGeneratedFiles.NotifyChatManager")
    @ResponseWrapper(localName = "notifyChatManagerResponse", targetNamespace = "http://webService.helper.sample/", className = "sample.helper.webService.wsGeneratedFiles.NotifyChatManagerResponse")
    @Action(input = "http://webService.helper.sample/NotificationsWebInterface/notifyChatManagerRequest", output = "http://webService.helper.sample/NotificationsWebInterface/notifyChatManagerResponse")
    public void notifyChatManager(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
