
package sample.helper.webService.wsGeneratedFiles;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NotificationsWebService", targetNamespace = "http://webService.helper.sample/", wsdlLocation = "http://localhost:9999/webService?wsdl")
public class NotificationsWebService
    extends Service
{

    private final static URL NOTIFICATIONSWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException NOTIFICATIONSWEBSERVICE_EXCEPTION;
    private final static QName NOTIFICATIONSWEBSERVICE_QNAME = new QName("http://webService.helper.sample/", "NotificationsWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/webService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTIFICATIONSWEBSERVICE_WSDL_LOCATION = url;
        NOTIFICATIONSWEBSERVICE_EXCEPTION = e;
    }

    public NotificationsWebService() {
        super(__getWsdlLocation(), NOTIFICATIONSWEBSERVICE_QNAME);
    }

    public NotificationsWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTIFICATIONSWEBSERVICE_QNAME, features);
    }

    public NotificationsWebService(URL wsdlLocation) {
        super(wsdlLocation, NOTIFICATIONSWEBSERVICE_QNAME);
    }

    public NotificationsWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTIFICATIONSWEBSERVICE_QNAME, features);
    }

    public NotificationsWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificationsWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NotificationsWebInterface
     */
    @WebEndpoint(name = "NotificationsWebPort")
    public NotificationsWebInterface getNotificationsWebPort() {
        return super.getPort(new QName("http://webService.helper.sample/", "NotificationsWebPort"), NotificationsWebInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificationsWebInterface
     */
    @WebEndpoint(name = "NotificationsWebPort")
    public NotificationsWebInterface getNotificationsWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService.helper.sample/", "NotificationsWebPort"), NotificationsWebInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTIFICATIONSWEBSERVICE_EXCEPTION!= null) {
            throw NOTIFICATIONSWEBSERVICE_EXCEPTION;
        }
        return NOTIFICATIONSWEBSERVICE_WSDL_LOCATION;
    }

}
