
package sample.helper.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NotificationsWebServiceService", targetNamespace = "http://webService.helper.sample/", wsdlLocation = "http://localhost:9999/webService?wsdl")
public class NotificationsWebServiceService
    extends Service
{

    private final static URL NOTIFICATIONSWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException NOTIFICATIONSWEBSERVICESERVICE_EXCEPTION;
    private final static QName NOTIFICATIONSWEBSERVICESERVICE_QNAME = new QName("http://webService.helper.sample/", "NotificationsWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/webService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTIFICATIONSWEBSERVICESERVICE_WSDL_LOCATION = url;
        NOTIFICATIONSWEBSERVICESERVICE_EXCEPTION = e;
    }

    public NotificationsWebServiceService() {
        super(__getWsdlLocation(), NOTIFICATIONSWEBSERVICESERVICE_QNAME);
    }

    public NotificationsWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTIFICATIONSWEBSERVICESERVICE_QNAME, features);
    }

    public NotificationsWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, NOTIFICATIONSWEBSERVICESERVICE_QNAME);
    }

    public NotificationsWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTIFICATIONSWEBSERVICESERVICE_QNAME, features);
    }

    public NotificationsWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificationsWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NotificationsWebInterface
     */
    @WebEndpoint(name = "NotificationsWebServicePort")
    public NotificationsWebInterface getNotificationsWebServicePort() {
        return super.getPort(new QName("http://webService.helper.sample/", "NotificationsWebServicePort"), NotificationsWebInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificationsWebInterface
     */
    @WebEndpoint(name = "NotificationsWebServicePort")
    public NotificationsWebInterface getNotificationsWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService.helper.sample/", "NotificationsWebServicePort"), NotificationsWebInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTIFICATIONSWEBSERVICESERVICE_EXCEPTION!= null) {
            throw NOTIFICATIONSWEBSERVICESERVICE_EXCEPTION;
        }
        return NOTIFICATIONSWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
